### PR TITLE
Node module resolution

### LINKED ISSUE #255: Add recommendations if there is a missing file
A lot of users issues are related to errors like
`crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: @openzeppelin/...`

Which is usually a sign that `npm install`/`yarn install` had an issue, or the files where installed somewhere else. We could improve the error message with recommendations like:
- Check if `ls <path to file>`
- Run `npm install` / `yarn install`

### LINKED ISSUE #258: Bug: monorepo package cannot find "@openzeppelin" etc
Originally reported at https://github.com/crytic/echidna/issues/738

For monorepos, after yarn install under the root folder, openzepplin is under the root folder node_modules:

We fixed this by applying a workround in :

https://github.com/superfluid-finance/protocol-monorepo/blob/echidna_fuzzing_integration/packages/hot-fuzz/fuzz.sh

```
# Apply a workaround due to https://github.com/crytic/echidna/issues/738
mkdir -p node_modules
ln -sf ../../../node_modules/\@superfluid-finance node_modules/
ln -sf ../../../node_modules/\@openzeppelin node_modules/
```

### LINKED ISSUE #262: Foundry - Slither / Unknown file console.sol
I am trying to add Slither to the Forge template [here](https://github.com/foundry-rs/forge-template/pull/49), and getting an unexpected error:

```
ERROR:CryticCompile:Unknown file: /home/runner/work/forge-template/forge-template/lib/forge-std/src/console.sol
```

It seems to be related to [this](https://github.com/crytic/crytic-compile/blob/35d95d6cb7716290ff4bf21ba9dcc8e582c6ee04/crytic_compile/utils/naming.py#L109-L117)?

I also wonder why `forge-template` appears twice in the path?

(Separately, the Slither action does not seem to error when it hits an Error, and it makes you think that it fails at the followup step, [here the SARIF upload](https://github.com/foundry-rs/forge-template/runs/6207682054?check_suite_focus=true))

### LINKED ISSUE #279: Fix detection of node_modules/ in monorepos
We need a way to find node_modules for monorepo that is more robust
This is especially sticky for monorepo projects where something like `@openzeppelin/*` is not installed in the relative `node_modules/` but in the root workspace.  Yarn 2 removed nohoist as well, so I haven't really found a good solution to this yet.  

A temporary workaround is to symlink the relevant packages into the relative/workspace's `node_modules/` dir but that gets pretty annoying and is temporary.

ETA:  A solution is adding the following to the `package.json` for the contract package:

    "installConfig": {
      "hoistingLimits": "dependencies"
    },

_Originally posted by @mikeshultz in https://github.com/crytic/slither/issues/852#issuecomment-1112361513_

### LINKED ISSUE #290: solc_remap cannot find contract at remap path?
cryptic-compile is failing to include an `@openzeppelin` contract that is installed in parent directory. I've tried to remap the path with `--solc-remaps` It consistently fails.
```
crytic-compile --hardhat-artifacts-directory ./build/contracts --solc-remaps '@openzeppelin/contracts/utils/Context.sol=../../node_modules/@openzeppelin/contracts/utils/Context.sol' .
INFO:CryticCompile:'npx hardhat compile --force' running
INFO:CryticCompile:Generating typings for: 50 artifacts in dir: ./build/typechain for target: ethers-v5
Successfully generated 150 typings!
Compiled 33 Solidity files successfully

ERROR:CryticCompile:(node:72314) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

ERROR:CryticCompile:Unknown file: @openzeppelin/contracts/utils/Context.sol
```

I can confirm that the `@openzeppelin` module is at that remap path

```
kevzettler@kevs-mbp-3 contracts % stat ../../node_modules/@openzeppelin/contracts/utils/Context.sol
16777232 61435240 -rw-r--r-- 1 kevzettler staff 0 844 "Sep 21 22:13:31 2022" "Sep 21 22:13:23 2022" "Sep 21 22:13:23 2022" "Sep 21 22:13:23 2022" 4096 8 0 ../../node_modules/@openzeppelin/contracts/utils/Context.sol
```

This project is a mono repo so the `node_modules` live in parent directory. I see there is some discussion about better monorepo support. Is this related to https://github.com/crytic/crytic-compile/issues/279 ? 

This project also uses a nonstandard hard hat artifact directory configured with `--hardhat-artifacts-directory` is that contributing to the problem?

### LINKED ISSUE #305: crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/interfaces/ICostModel.sol
Unfortunately the repo is not open source at the moment (though @0xicingdeath @rmi7 and @damilolaedwards currently have access), but I can summarize the folder structure that caused the issue:

- RootRepo has RepoModels as a submodule
- RepoModels has RepoInterfaces as a submodule
- All paths use "absolute" paths, e.g. `src/interfaces/ICostModel.sol`, and not `./ICostModel.sol`. Personally I prefer this because it's more clear, and simplifies moving files around.

When running `slither .` on RootRepo I receive the following error. Changing import paths from absolute to relative solves the issue. The repo compiles successfully with `forge build`, but it seems slither has issues resolving the remappings, what I believe is happening is:
- It can't find `src/interfaces/ICostModel.sol`, because that doesn't exist (i.e. `RootRepo/src/interfaces/ICostModel.sol` is where that's pointing)
- It should be looking in `RootRepo/lib/RepoModels/lib/RepoInterfaces/src/interfaces/ICostModel.sol`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 117, in compile
    filename = convert_filename(
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/interfaces/ICostModel.sol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 86, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 124, in compile
    raise InvalidCompilation(txt)
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/interfaces/ICostModel.sol
Something went wrong, please open an issue in https://github.com/crytic/crytic-compile
Error in .
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 117, in compile
    filename = convert_filename(
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/interfaces/ICostModel.sol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 86, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 124, in compile
    raise InvalidCompilation(txt)
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/interfaces/ICostModel.sol
Something went wrong, please open an issue in https://github.com/crytic/crytic-compile
```

### LINKED ISSUE #321: ERROR:CryticCompile:Unknown file: @openzeppelin/contracts/access/Ownable.sol
--solc-args "--base-path /xxxx/  --include-path /xxxx/node_modules/" 

still cannot find @openzeppelin/contracts/access/Ownable.sol

### PR DESCRIPTION
**Pull request by bohendo**
Fixes issues related to improper resolution of dependencies from `node_modules`:

fixes #279
fixes #258 
fixes #321 
fixes #305 
fixes #290 
fixes #255

### CODE REVIEW

File: scripts/ci_test_brownie.sh [hunk 1]
```diff
@@ -1,13 +1,15 @@
...
-crytic-compile . --compile-force-framework Brownie
+cd token || exit 255
 
-if [ $? -ne 0 ]
-then
-    echo "Brownie test failed"
-    exit 255
+if ! crytic-compile . --compile-force-framework Brownie
+then echo "Brownie test failed" && exit 255
+else echo "Brownie test passed" && exit 0
```
Comment (bohendo) [inline scripts/ci_test_brownie.sh:14]: Unrelated to core issue resolutions: I used `shellcheck` to lint all CI test scripts

Comment (bohendo) [reply scripts/ci_test_brownie.sh]: nvmd, CI broke so hopefully reverting these changes will help debug automated tests

File: pyproject.toml [hunk 2]
```diff
@@ -11,6 +11,7 @@ invalid-name,
 fixme,
 too-many-return-statements,
 too-many-ancestors,
+too-many-statements,
```
Comment (montyly) [inline pyproject.toml:14]: I am not sure about removing this warning. If pylint raises this its usually because a function would benefit from being split between internal functions
